USE [master]
GO
/****** Object:  Database [Sistema_Ventas_Analitica]    Script Date: 19/4/2026 1:28:51 p. m. ******/
CREATE DATABASE [Sistema_Ventas_Analitica]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sistema_Ventas_Analitica', FILENAME = N'C:\Users\kevin\Sistema_Ventas_Analitica.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sistema_Ventas_Analitica_log', FILENAME = N'C:\Users\kevin\Sistema_Ventas_Analitica_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sistema_Ventas_Analitica].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET  MULTI_USER 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET QUERY_STORE = ON
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Sistema_Ventas_Analitica]
GO
/****** Object:  Table [dbo].[Dim_Cliente]    Script Date: 19/4/2026 1:28:51 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Cliente](
	[ID_Cliente] [int] NOT NULL,
	[Nombre_Cliente] [varchar](150) NOT NULL,
	[Tipo_Cliente] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Producto]    Script Date: 19/4/2026 1:28:51 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Producto](
	[ID_Producto] [int] NOT NULL,
	[Nombre_Producto] [varchar](150) NOT NULL,
	[Categoria] [varchar](100) NOT NULL,
	[Precio_Base] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Tiempo]    Script Date: 19/4/2026 1:28:51 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Tiempo](
	[ID_Tiempo] [int] NOT NULL,
	[Fecha] [date] NOT NULL,
	[Anio] [int] NOT NULL,
	[Trimestre] [int] NOT NULL,
	[Mes] [int] NOT NULL,
	[Nombre_Mes] [varchar](20) NOT NULL,
	[Dia] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Tiempo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dim_Ubicacion]    Script Date: 19/4/2026 1:28:51 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dim_Ubicacion](
	[ID_Ubicacion] [int] NOT NULL,
	[Pais] [varchar](100) NOT NULL,
	[Region] [varchar](100) NOT NULL,
	[Ciudad] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Ubicacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Fact_Ventas]    Script Date: 19/4/2026 1:28:51 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fact_Ventas](
	[ID_Venta] [int] IDENTITY(1,1) NOT NULL,
	[ID_Transaccion] [int] NOT NULL,
	[ID_Tiempo] [int] NOT NULL,
	[ID_Producto] [int] NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[ID_Ubicacion] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[Precio_Unitario] [decimal](10, 2) NOT NULL,
	[Total_Venta] [decimal](10, 2) NOT NULL,
	[Origen_Datos] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Venta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Fact_Ventas]  WITH CHECK ADD FOREIGN KEY([ID_Cliente])
REFERENCES [dbo].[Dim_Cliente] ([ID_Cliente])
GO
ALTER TABLE [dbo].[Fact_Ventas]  WITH CHECK ADD FOREIGN KEY([ID_Producto])
REFERENCES [dbo].[Dim_Producto] ([ID_Producto])
GO
ALTER TABLE [dbo].[Fact_Ventas]  WITH CHECK ADD FOREIGN KEY([ID_Tiempo])
REFERENCES [dbo].[Dim_Tiempo] ([ID_Tiempo])
GO
ALTER TABLE [dbo].[Fact_Ventas]  WITH CHECK ADD FOREIGN KEY([ID_Ubicacion])
REFERENCES [dbo].[Dim_Ubicacion] ([ID_Ubicacion])
GO
USE [master]
GO
ALTER DATABASE [Sistema_Ventas_Analitica] SET  READ_WRITE 
GO
